# Generated by Django 3.2.4 on 2021-06-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counter1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('billing_rates', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grace_period', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('loan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_address', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('dependents', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sharecapital_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('membership_number', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('id_back', models.CharField(blank=True, max_length=1000, null=True)),
                ('loan_limit', models.CharField(choices=[('1,000-5,000', '1000-5000'), ('6,000-1,0000', '6000-10000'), ('11,000-20,000', '11000-20000'), ('21,000-30,000', '21000-30000')], default='1,000-5,000', max_length=100000)),
                ('automatic', models.BooleanField(default=False)),
                ('action_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('first_verification', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter1.clients')),
            ],
        ),
    ]
