# Generated by Django 3.2.4 on 2021-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter1', '0002_billing_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='loan_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
